baseURL = 'https://fubark.github.io/cyber'
languageCode = 'en-us'
title = 'Cyber Docs v0.2'
theme = 'hugo-book'

# Allow html
#[markup.goldmark.renderer]
#unsafe = true

[menu]
[[menu.before]]
  name = "Homepage"
  url = "https://cyberscript.dev"
  weight = 1
[[menu.before]]
  name = "Playground"
  url = "https://cyberscript.dev/play.html"
  weight = 2
# [[menu.after]]

[params]
BookTheme = 'dark'
BookRepo = 'https://github.com/fubark/cyber'
BookEditPath = 'edit/master/docs/hugo'