baseURL = 'https://fubark.github.io/cyber'
languageCode = 'en-us'
title = 'Cyber Docs v0.1'
theme = 'hugo-book'

[params]
BookTheme = 'light'
BookRepo = 'https://github.com/fubark/cyber'
BookEditPath = 'edit/master/docs/hugo'