name: Gen Docs

on:
  workflow_dispatch:
  push:
    branches:
      - master
    paths:
      - 'docs/hugo/**'
jobs:
  deploy:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: false
          fetch-depth: 0    # Fetch all history for .GitInfo and .Lastmod

      - name: Install theme.
        run: |
          git clone --depth=1 https://github.com/alex-shpak/hugo-book docs/hugo/themes/hugo-book

      - name: Install Hugo.
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: 'latest'
          # Needed to build SCSS/SASS with transpiler set to 'libsass'
          extended: true

      - name: Generate.
        run: |
          cd docs/hugo
          hugo --minify

      - name: Deploy.
        uses: peaceiris/actions-gh-pages@v3
        if: github.ref == 'refs/heads/master'
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs/hugo/public